### ISSUE TITLE
error when adding zoom-view to img element in ng-repeat

### ISSUE THREAD

**Issue by spi7fire** [AlexDisler/ionic-zoom-view#7]
the elem arrives to the directive is an array, so browser throws exception:

angular.js:11607 TypeError: element.setAttribute is not a function
    at forEach.attr (http://localhost:8100/lib/angular/angular.js:2869:15)
    at Object.JQLite.(anonymous function) [as attr] (http://localhost:8100/lib/angular/angular.js:2968:9)
    at Object.Attributes.$set (http://localhost:8100/lib/angular/angular.js:6790:28)
    at Object.interpolateFnWatchAction (http://localhost:8100/lib/angular/angular.js:8118:28)
    at Object.arguments.(anonymous function) (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1997:36)
    at Object.applyFunction [as fn] (<anonymous>:778:50)
    at Scope.$digest (http://localhost:8100/lib/angular/angular.js:14243:29)
    at Scope.$delegate.__proto__.$digest (<anonymous>:844:31)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2016:23)
    at Scope.$apply (http://localhost:8100/lib/angular/angular.js:14506:24)

code:

          <div ng-repeat="pet in user.Pets | unique:'id' track by $index" class="clearfix pet">
            <div class="image">
              <img class="img-responsive" ng-src="{{uploadpath}}{{pet.info.profile}}-thumb.jpg"
                   zoom-src="{{uploadpath}}{{user.Pets.info.profile}}.jpg" zoom-view />
              ...

**Comment by spi7fire** [comment]
Found the problem (And the solution):
i replaced ng-if with ng-show
